const c = require('./core.js'); const assert = require('assert');
assert.equal(c.compare([1, 0, 0], [1, 1, 0]), 'before');
assert.equal(c.compare([1, 0, 1], [0, 1, 1]), 'concurrent');
assert.equal(c.compare([2], [2, 0, 0]), 'same');
assert.equal(c.happensBefore([0, 1], [0, 2]), true);
assert.deepEqual(c.merge([1, 0, 0], [0, 2], 0), [2, 2, 0]);
assert.deepEqual(c.tick([0, 0], 1), [0, 1]);
assert.equal(c.format([2, 1, 0]), '<2,1,0>');
assert.throws(() => c.tick([0, -1], 0), /non-negative/);
assert.throws(() => c.compare([1, 'x'], [1, 0]), /non-negative/);
const roundTrip = c.deserializeEvents(c.serializeEvents([{ id: 'a', replica: 0, clock: [1, 0], label: 'x', type: 'local' }]));
assert.deepEqual(roundTrip[0].clock, [1, 0]);
assert.throws(() => c.deserializeEvents({ version: 1, events: [{ replica: 0, clock: [1, -1] }] }), /non-negative/);
console.log('vector clock core tests: PASS (causality, validation, serialization)');
